AffineTransform: GLWindow Class Reference
GLWindow Class Reference
our main glwindow widget for NGL applications all drawing elements are put in this file
#include <GLWindow.h>
Public Slots
void vboChanged (int _index)
slot to indicate the vbo selection combo box has changed called from MainWindow
void toggleNormals (bool _value)
slot to indicate the normal tick box has been activated called from MainWindow
void toggleWireframe (bool _value)
slot to indicate the wireframe tick box has been activated called from MainWindow
void setNormalSize (int _value)
slot to indicate the normal length slider had changed called from MainWindow
void setScale (float _x, float _y, float _z)
called when any of the scale elements are modified sets the new m_scale matrix value and forces a re-calcuation and re-draw called from MainWindow
void setTranslate (float _x, float _y, float _z)
called when any of the translate elements are modified sets the new m_translate matrix value and forces a re-calcuation and re-draw called from MainWindow
void setRotate (float _x, float _y, float _z)
called when any of the rotate elements are modified sets the new m_rotate matrix value and forces a re-calcuation and re-draw called from MainWindow
void setColour (float _r, float _g, float _b)
called when the colour button is pressed and a new colour selected sets a new current material and forces update called from MainWindow
void setMatrixOrder (int _index)
called when the matrix order combobox is changed sets the new matrix order for m_matrixOrder and forces re-draw called from MainWindow
void setEuler (float _angle, float _x, float _y, float _z)
called when any of the euler rotation elements are modified sets the new m_euler matrix value and forces a re-calcuation and re-draw called from MainWindow
Signals
void matrixDirty (ngl::Mat4 _m)
signal emitted when the transform matrix is modified it is recived by the main window which will set the main matrix values
Public Member Functions
GLWindow (const QGLFormat _format, QWidget *_parent)
Constructor for GLWindow.
~GLWindow ()
void resetMouse ()
bool loadScene (const std::string &_path)
void renderScene (Renderer::RenderContext *_context)
Renderer::Scene * getScene ()
void createFramebufferObject ()
void createTextureObject ()
void setScenePath (const std::string &_path)
Public Attributes
std::vector< ngl::Vec3 > m_verts
std::string m_scenePath
ngl::Camera * m_cam
Our Camera.
ngl::VertexArrayObject * test_vao
QFuture< void > renderThread
Protected Member Functions
void initializeGL ()
The following methods must be implimented in the sub class this is called when the window is created.
void resizeGL (const int _w, const int _h)
this is called whenever the window is re-sized
void paintGL ()
this is the main gl drawing routine which is called whenever the window needs to be re-drawn
Private Types
enum MATRIXORDER {
RTS, TRS, GIMBALLOCK, EULERTS,
TEULERS
}
Private Member Functions
void mouseMoveEvent (QMouseEvent *_event)
this method is called every time a mouse is moved
void mousePressEvent (QMouseEvent *_event)
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
void mouseReleaseEvent (QMouseEvent *_event)
this method is called everytime the mouse button is released inherited from QObject and overridden here.
void wheelEvent (QWheelEvent *_event)
this method is called everytime the mouse wheel is moved inherited from QObject and overridden here.
void loadMatricesToShader ()
Private Attributes
GLuint m_textureID
our texture id used by the FBO
GLuint m_fboID
our FBO id used by the FBO
GLuint m_rboID
our render buffer id used by the FBO
int m_spinXFace
used to store the x rotation mouse value
int m_spinYFace
used to store the y rotation mouse value
bool m_rotateActive
flag to indicate if the Left mouse button is pressed when dragging
bool m_translateActive
flag to indicate if the Right mouse button is pressed when dragging
int m_origX
the previous x mouse value
int m_origY
the previous y mouse value
int m_origXPos
the previous x mouse value for Position changes
int m_origYPos
the previous y mouse value for Position changes
ngl::Vec3 m_modelPos
ngl::Mat4 m_mouseGlobalTX
used to store the global mouse transforms
int m_drawIndex
the index into the VBO name array for the drawing
bool m_drawNormals
flag to indicate if we draw the normals
ngl::Mat4 m_transform
the final transform matrix
ngl::Mat4 m_rotate
a matrix to hold the rotation
ngl::Mat4 m_gimbal
a matrix to demonstrate gimal locs
ngl::Mat4 m_translate
the translation matrix
ngl::Mat4 m_scale
the scale matrix
ngl::Mat4 m_euler
the Euler rotation matrix
ngl::Light * m_light
the light for the shading
ngl::Colour m_colour
the colour for the object material
int m_normalSize
the size to draw the normals
Axis * m_axis
the axis
ngl::Material m_material
Renderer::Scene * m_scene
MATRIXORDER m_matrixOrder
the order of multiplication for the transform matrix
Static Private Attributes
static const std::string s_vboNames [17]
static array of names used in the vbo drawing initialised in GLWindow.cpp
Detailed Description
our main glwindow widget for NGL applications all drawing elements are put in this file
Definition at line 36 of file GLWindow.h.
Member Enumeration Documentation
enum GLWindow::MATRIXORDER private
Enumerator
RTS
Rotate Translate Scale.
TRS
Translate Rotate Scale.
GIMBALLOCK
EULERTS
TEULERS
Definition at line 199 of file GLWindow.h.
                   {
                     RTS,
                     TRS,
                     GIMBALLOCK,
                     EULERTS, //< Use Axis Angle Euler Trans Scale
                     TEULERS //<  Use Translate Euler Scale
                   };
Constructor & Destructor Documentation
GLWindow::GLWindow (const QGLFormat _format, QWidget * _parent)
Constructor for GLWindow.
Parameters
[in] _parent the parent window to create the GL context in
set all our matrices to the identity
Definition at line 55 of file GLWindow.cpp.
References m_axis, m_cam, m_colour, m_drawIndex, m_drawNormals, m_euler, m_material, m_matrixOrder, m_modelPos, m_normalSize, m_origX, m_origY, m_rotate, m_rotateActive, m_scale, m_scene, m_scenePath, m_spinXFace, m_spinYFace, m_transform, m_translate, m_translateActive, and RTS.
                                                              : QGLWidget( _format, _parent )
 {
   // set this widget to have the initial keyboard focus
   setFocus();
   // re-size the widget to that of the parent (in this case the GLFrame passed in on construction)
   this->resize(_parent->size());
   // Now set the initial GLWindow attributes to default values
   // Roate is false
   m_rotateActive=false;
   m_translateActive=false;
   // mouse rotation values set to 0
   m_spinXFace=0;
   m_spinYFace=0;
   m_origX=0;
   m_origY=0;
   m_drawIndex=6;
   m_drawNormals=false;
   m_transform=1.0;
   m_rotate=1.0;
   m_translate=1.0;
   m_scale=1.0;
   m_normalSize=6.0;
   m_colour.set(0.5,0.5,0.5);
   m_material.setDiffuse(m_colour);
   m_material.setSpecular(ngl::Colour(0.2,0.2,0.2));
   m_material.setAmbient(ngl::Colour());
   m_material.setSpecularExponent(20);
   m_material.setRoughness(0);
   m_matrixOrder=GLWindow::RTS;
   m_euler=1.0;
   m_modelPos.set(0,0,0);
   m_cam = NULL;
   m_axis = NULL;
   m_scene = NULL;
   m_scenePath = "test.tray";
 }
GLWindow::~GLWindow () inline
Definition at line 48 of file GLWindow.h.
   {
 //    renderThread.cancel();
 //    renderThread.waitForFinished();
   }
Member Function Documentation
void GLWindow::createFramebufferObject ()
void GLWindow::createTextureObject ()
Renderer::Scene* GLWindow::getScene () inline
Definition at line 60 of file GLWindow.h.
References m_scene.
 { return m_scene; }
void GLWindow::initializeGL () protected
The following methods must be implimented in the sub class this is called when the window is created.
now create our primitives for drawing later
Definition at line 143 of file GLWindow.cpp.
References loadScene(), m_axis, m_cam, m_light, and Axis::setCam().
 {
   ngl::NGLInit::instance();
   glClearColor(0.4f, 0.4f, 0.4f, 1.0f);        // Grey Background
   // enable depth testing for drawing
   glEnable(GL_DEPTH_TEST);
   glEnable(GL_CULL_FACE);
   glCullFace(GL_FRONT);
   // Now we will create a basic Camera from the graphics library
   // This is a static camera so it only needs to be set once
   // First create Values for the camera position
   //ngl::Vec3 from(48, 14, 0);
   ngl::Vec3 from(48, 14, 0);
   ngl::Vec3 to(0,14,0);
   ngl::Vec3 up(0,1,0);
   m_cam= new ngl::Camera(from,to,up);
   // set the shape using FOV 45 Aspect Ratio based on Width and Height
   // The final two are near and far clipping planes of 0.5 and 10
   m_cam->setShape(45,(float)720.0/576.0, 0.5, 10);
   // now to load the shader and set the values
   // grab an instance of shader manager
   ngl::ShaderLib *shader=ngl::ShaderLib::instance();
   // we are creating a shader called Phong
   shader->createShaderProgram("Phong");
   // now we are going to create empty shaders for Frag and Vert
   shader->attachShader("PhongVertex",ngl::VERTEX);
   shader->attachShader("PhongFragment",ngl::FRAGMENT);
   // attach the source
   shader->loadShaderSource("PhongVertex","shaders/PhongVertex.glsl");
   shader->loadShaderSource("PhongFragment","shaders/PhongFragment.glsl");
   // compile the shaders
   shader->compileShader("PhongVertex");
   shader->compileShader("PhongFragment");
   // add them to the program
   shader->attachShaderToProgram("Phong","PhongVertex");
   shader->attachShaderToProgram("Phong","PhongFragment");
   // now bind the shader attributes for most NGL primitives we use the following
   // layout attribute 0 is the vertex data (x,y,z)
   // as we now use glsl 400 and layout qualifiers we don't need this anymore
 //  shader->bindAttribute("Phong",0,"inVert");
 //  // attribute 1 is the UV data u,v (if present)
 //  shader->bindAttribute("Phong",1,"inUV");
 //  // attribute 2 are the normals x,y,z
 //  shader->bindAttribute("Phong",2,"inNormal");
   // now we have associated this data we can link the shader
   shader->linkProgramObject("Phong");
   // and make it active ready to load values
   (*shader)["Phong"]->use();
   // now create our light this is done after the camera so we can pass the
   // transpose of the projection matrix to the light to do correct eye space
   // transformations
   ngl::Mat4 iv=m_cam->getProjectionMatrix();
   iv.transpose();
   m_light = new ngl::Light(ngl::Vec3(-2,2,-2),ngl::Colour(1,1,1,1),ngl::Colour(1,1,1,1),ngl::POINTLIGHT);
   m_light->setTransform(iv);
   // load these values to the shader as well
   m_light->loadToShader("light");
   shader->createShaderProgram("Colour");
    shader->attachShader("ColourVertex",ngl::VERTEX);
    shader->attachShader("ColourFragment",ngl::FRAGMENT);
    shader->loadShaderSource("ColourVertex","shaders/ColourVertex.glsl");
    shader->loadShaderSource("ColourFragment","shaders/ColourFragment.glsl");
    shader->compileShader("ColourVertex");
    shader->compileShader("ColourFragment");
    shader->attachShaderToProgram("Colour","ColourVertex");
    shader->attachShaderToProgram("Colour","ColourFragment");
    // as we now use glsl 400 and layout qualifiers we don't need this anymore
   //   shader->bindAttribute("Colour",0,"inVert");
   //   shader->bindAttribute("Colour",1,"inUV");
   //   shader->bindAttribute("Colour",2,"inNormal");
    shader->linkProgramObject("Colour");
    (*shader)["Colour"]->use();
   ngl::VAOPrimitives *prim=ngl::VAOPrimitives::instance();
   prim->createSphere("sphere",1.0,40);
   prim->createCylinder("cylinder",0.5,1.4,40,40);
   prim->createCone("cone",0.5,1.4,20,20);
   prim->createDisk("disk",0.5,40);
   prim->createTrianglePlane("plane",1,1,10,10,ngl::Vec3(0,1,0));
   prim->createTorus("torus",0.15,0.4,40,40);
   prim->createLineGrid("grid", 20, 20, 20);
   prim->createTrianglePlane("viewport",1,1,1,1,ngl::Vec3(0,1,0));
   // set the bg colour
   glClearColor(0.5,0.5,0.5,0.0);
   m_axis = new Axis("Colour",1.5);
   m_axis->setCam(m_cam);
   // load the normal shader
   shader->createShaderProgram("normalShader");
   shader->attachShader("normalVertex",ngl::VERTEX);
   shader->attachShader("normalFragment",ngl::FRAGMENT);
   shader->loadShaderSource("normalVertex","shaders/normalVertex.glsl");
   shader->loadShaderSource("normalFragment","shaders/normalFragment.glsl");
   shader->compileShader("normalVertex");
   shader->compileShader("normalFragment");
   shader->attachShaderToProgram("normalShader","normalVertex");
   shader->attachShaderToProgram("normalShader","normalFragment");
   shader->attachShader("normalGeo",ngl::GEOMETRY);
   shader->loadShaderSource("normalGeo","shaders/normalGeo.glsl");
   shader->compileShader("normalGeo");
   shader->attachShaderToProgram("normalShader","normalGeo");
   // as we now use glsl 400 and layout qualifiers we don't need this anymore
 //  shader->("normalShader",0,"inVert");
 //  shader->bindAttribute("normalShader",1,"inUV");
 //  shader->bindAttribute("normalShader",2,"inNormal");
   shader->linkProgramObject("normalShader");
   shader->use("normalShader");
   // now pass the modelView and projection values to the shader
   shader->setShaderParam1f("normalSize",0.1);
   shader->setShaderParam4f("vertNormalColour",1,1,0,1);
   shader->setShaderParam4f("faceNormalColour",1,0,0,1);
   shader->setShaderParam1i("drawFaceNormals",true);
   shader->setShaderParam1i("drawVertexNormals",true);
   //prim->createSphere("sphere1", 1.0f, 30);
   loadScene("test.tray");
 //  createTextureObject();
 //  createFramebufferObject();
 //  std::function<float(float)> F = [](float x){ return 2 * x * x; } ;
 //  std::function<float(float)> f = [](float x){ return 4 * x; } ;
 //  float result = integrate(F, f, 0, 5, 100);
 //  qDebug() << result;
   // create the m_points array for drawing the quad as a tri
 //    GLubyte indices[]={0,1,3,3,2,1};
 //    (*shader)["Phong"]->use();
 //    shader->setRegisteredUniform4f("Colour",1,1,0,0);
 //    test_vao = ngl::VertexArrayObject::createVOA(GL_TRIANGLES);
 //    test_vao->bind();
 //    test_vao->setIndexedData(4*sizeof(ngl::Vec3),m_verts[0].m_x,sizeof(indices),&indices[0],GL_UNSIGNED_BYTE);
 //    test_vao->setVertexAttributePointer(0,3,GL_FLOAT,sizeof(ngl::Vec3),0);
 //    test_vao->setIndexedData(4*sizeof(ngl::Vec3),normals[0].m_x,sizeof(indices),&indices[0],GL_UNSIGNED_BYTE);
 //    test_vao->setVertexAttributePointer(2,3,GL_FLOAT,sizeof(ngl::Vec3),0);
 //    test_vao->setNumIndices(6);
 }
void GLWindow::loadMatricesToShader () private
Definition at line 313 of file GLWindow.cpp.
References m_cam, m_mouseGlobalTX, and m_transform.
 {
   ngl::ShaderLib *shader=ngl::ShaderLib::instance();
   (*shader)["Phong"]->use();
   ngl::Mat4 MV;
   ngl::Mat4 MVP;
   ngl::Mat3 normalMatrix;
   ngl::Mat4 M;
   M = m_transform * m_mouseGlobalTX;
   MV = M * m_cam->getViewMatrix();
   MVP = MV * m_cam->getProjectionMatrix();
   normalMatrix=MV;
   normalMatrix.inverse();
   shader->setShaderParamFromMat4("MV",MV);
   shader->setShaderParamFromMat4("MVP",MVP);
   shader->setShaderParamFromMat3("normalMatrix",normalMatrix);
   shader->setShaderParamFromMat4("M",M);
 }
bool GLWindow::loadScene (const std::string & _path)
Definition at line 457 of file GLWindow.cpp.
References m_scene, and Renderer::SceneFile::read().
 {
     try
     {
         Renderer::SceneFile file(_filepath);
         m_scene = file.read();
     }
     catch(std::invalid_argument& e)
     {
         std::cerr << e.what() << std::endl;
         return false;
     }
     return true;
 }
void GLWindow::matrixDirty (ngl::Mat4 _m) signal
signal emitted when the transform matrix is modified it is recived by the main window which will set the main matrix values
Parameters
_m the new transformation values used in the display
void GLWindow::mouseMoveEvent (QMouseEvent * _event) private
this method is called every time a mouse is moved
Parameters
_event the Qt Event structure
Definition at line 489 of file GLWindow.cpp.
References m_cam, m_origX, m_origXPos, m_origY, m_origYPos, m_rotateActive, m_spinXFace, m_spinYFace, and m_translateActive.
 {
   // note the method buttons() is the button state when event was called
   // this is different from button() which is used to check which button was
   // pressed when the mousePress/Release event is generated
   if(m_rotateActive && _event->buttons() == Qt::LeftButton)
   {
     m_spinYFace = ( m_spinYFace + (_event->x() - m_origX) ) % 360 ;
     m_spinXFace = ( m_spinXFace + (_event->y() - m_origY) ) % 360 ;
     m_origX = _event->x();
     m_origY = _event->y();
     updateGL();
   }
   // right mouse translate code
   else if(m_translateActive && _event->buttons() == Qt::RightButton)
   {
     int diffX = (int)(_event->x() - m_origXPos);
     int diffY = (int)(_event->y() - m_origYPos);
     m_origXPos=_event->x();
     m_origYPos=_event->y();
 //    m_modelPos.m_x += INCREMENT * diffX;
 //    m_modelPos.m_y -= INCREMENT * diffY;
     m_cam->slide(-diffX * 0.1f, diffY * 0.1f, 0);
     updateGL();
   }
 }
void GLWindow::mousePressEvent (QMouseEvent * _event) private
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
Parameters
_event the Qt Event structure
Definition at line 522 of file GLWindow.cpp.
References m_origX, m_origXPos, m_origY, m_origYPos, m_rotateActive, and m_translateActive.
 {
   // this method is called when the mouse button is pressed in this case we
   // store the value where the maouse was clicked (x,y) and set the Rotate flag to true
   if(_event->button() == Qt::LeftButton)
   {
     m_origX = _event->x();
     m_origY = _event->y();
     m_rotateActive =true;
   }
   // right mouse translate mode
   else if(_event->button() == Qt::RightButton)
   {
     m_origXPos = _event->x();
     m_origYPos = _event->y();
     m_translateActive=true;
   }
 }
void GLWindow::mouseReleaseEvent (QMouseEvent * _event) private
this method is called everytime the mouse button is released inherited from QObject and overridden here.
Parameters
_event the Qt Event structure
Definition at line 543 of file GLWindow.cpp.
References m_rotateActive, and m_translateActive.
 {
   // this event is called when the mouse button is released
   // we then set Rotate to false
   if (_event->button() == Qt::LeftButton)
   {
     m_rotateActive=false;
   }
   // right mouse translate mode
   if (_event->button() == Qt::RightButton)
   {
     m_translateActive=false;
   }
 }
void GLWindow::paintGL () protected
this is the main gl drawing routine which is called whenever the window needs to be re-drawn
Definition at line 335 of file GLWindow.cpp.
References Axis::draw(), Renderer::Scene::getBackgroundColour(), loadMatricesToShader(), loadScene(), m_axis, Image::Pixel::m_b, Image::Pixel::m_g, m_light, m_material, m_modelPos, m_mouseGlobalTX, Image::Pixel::m_r, m_scene, m_scenePath, m_spinXFace, m_spinYFace, m_transform, Renderer::Scene::objectBegin(), and Renderer::Scene::objectEnd().
 {
     // Reload the scene every draw, not very efficient but it does allow for easy file editing
     QFileInfo checkFile(QString(m_scenePath.c_str()));
     if(checkFile.exists() && checkFile.isFile())
     {
       loadScene(m_scenePath);
     }
     else
     {
       qWarning("Scene file %s does not exist", m_scenePath.c_str());
       return;
     }
 //    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
 //    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
 //    (*shader)["Phong"]->use();
 //    ngl::Mat4 MV;
 //    ngl::Mat4 MVP;
 //    ngl::Mat3 normalMatrix;
 //    ngl::Mat4 M;
 //    MV = M * m_cam->getViewMatrix();
 //    //MV.rotateX(90);
 //    MVP.rotateX(-90);
 //    normalMatrix=MV;
 //    normalMatrix.inverse();
 //    shader->setShaderParamFromMat4("MV",MV);
 //    shader->setShaderParamFromMat4("MVP",MVP);
 //    shader->setShaderParamFromMat3("normalMatrix",normalMatrix);
 //    shader->setShaderParamFromMat4("M",M);
 //    (*shader)["Phong"]->use();
 //    m_material.setDiffuse(ngl::Colour());
 //    m_material.setAmbient(ngl::Colour(1,1,1,1));
 //    m_material.setSpecularExponent(0);
 //    m_material.setSpecular(ngl::Colour());
 //    // now set this value in the shader for the current ModelMatrix
 //    m_material.loadToShader("material");
 //    glBindTexture(GL_TEXTURE_2D, m_textureID);
 //    ngl::VAOPrimitives *prim=ngl::VAOPrimitives::instance();
 //    prim->draw("viewport");
 //    return;
 //  glBindFramebuffer(GL_FRAMEBUFFER, m_fboID);
 //  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
 //  glViewport(0, 0, TEXTURE_WIDTH, TEXTURE_HEIGHT);
 //  glBindFramebuffer(GL_FRAMEBUFFER, 0);
   // grab an instance of the shader manager
   ngl::ShaderLib *shader=ngl::ShaderLib::instance();
   // clear the screen and depth buffer
   glClearColor( m_scene->getBackgroundColour().m_r, m_scene->getBackgroundColour().m_g, m_scene->getBackgroundColour().m_b, 1);
   glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
   // Rotation based on the mouse position for our global
   // transform
   m_light->enable();
   m_transform.identity();
   loadMatricesToShader();
   (*shader)["Phong"]->use();
   // now set this value in the shader for the current ModelMatrix
   m_material.loadToShader("material");
   // Rotation based on the mouse position for our global transform
   ngl::Mat4 rotX;
   ngl::Mat4 rotY;
   // create the rotation matrices
   rotX.rotateZ(m_spinXFace / 3.f);
   rotY.rotateY(m_spinYFace);
   // multiply the rotations
   m_mouseGlobalTX=rotY * rotX;
   // add the translations
   m_mouseGlobalTX.m_m[3][0] = m_modelPos.m_x;
   m_mouseGlobalTX.m_m[3][1] = m_modelPos.m_y;
   m_mouseGlobalTX.m_m[3][2] = m_modelPos.m_z;
   loadMatricesToShader();
   // get the VBO instance and draw the built in teapot
   ngl::VAOPrimitives *prim=ngl::VAOPrimitives::instance();
   if(m_scene)
   {
       (*shader)["Phong"]->use();
       using namespace Renderer;
       for( Scene::objectListIterator object = m_scene->objectBegin();
            object != m_scene->objectEnd();
            ++object)
       {
         m_transform = (*object)->worldTransform();
         loadMatricesToShader();
         m_material.setDiffuse((*object)->getSurfaceMaterial().m_diffuse);
         m_material.loadToShader("material");
         (*object)->draw();
       }
   }
   m_axis->draw(m_mouseGlobalTX);
   m_transform.identity();
   loadMatricesToShader();
   m_material.setDiffuse(ngl::Colour(0,0,0));
   m_material.loadToShader("material");
   prim->draw("grid");
 }
void GLWindow::renderScene (Renderer::RenderContext * _context)
Todo:
Clean up the scene/render context confusion
Todo:
Stop render when main QT window is closed
Definition at line 473 of file GLWindow.cpp.
References m_cam, m_mouseGlobalTX, Renderer::RenderContext::m_renderCamera, m_scene, Renderer::render(), and renderThread.
  {
    if(m_scene != NULL)
    {
      ngl::Mat4 tmp = m_mouseGlobalTX * m_cam->getViewMatrix();
      _context->m_renderCamera = new Renderer::Camera(tmp.inverse(), m_cam->getFOV());
      // render in a separate thread
      renderThread = QtConcurrent::run(Renderer::render, _context);
    }
  }
void GLWindow::resetMouse ()
Definition at line 684 of file GLWindow.cpp.
References m_origX, m_origY, m_spinXFace, and m_spinYFace.
 {
   m_spinXFace=0;
   m_spinYFace=0;
   m_origX=0;
   m_origY=0;
   updateGL();
 }
void GLWindow::resizeGL (const int _w, const int _h) protected
this is called whenever the window is re-sized
Parameters
[in] _w the width of the resized window
[in] _h the height of the resized window
Definition at line 306 of file GLWindow.cpp.
References m_cam.
 {
   glViewport(0,0,_w,_h);
   m_cam->setShape(45,(float)_w/_h,0.05,10000);
 }
void GLWindow::setColour (float _r, float _g, float _b) slot
called when the colour button is pressed and a new colour selected sets a new current material and forces update called from MainWindow
Parameters
[in] _r the value of red
[in] _g the value of green
[in] _b the value of blue
Definition at line 651 of file GLWindow.cpp.
References m_colour, and m_material.
 {
   m_colour.set(_r,_g,_b);
   m_material.setDiffuse(m_colour);
   m_material.loadToShader("material");
   updateGL();
 }
void GLWindow::setEuler (float _angle, float _x, float _y, float _z) slot
called when any of the euler rotation elements are modified sets the new m_euler matrix value and forces a re-calcuation and re-draw called from MainWindow
Parameters
[in] _angle the angle in degrees
[in] _x the value of rotation axis [-1 , 1]
[in] _y the value of rotation axis [-1 , 1]
[in] _z the value of rotation axis [-1 , 1]
Definition at line 676 of file GLWindow.cpp.
References m_euler.
 {
   m_euler=1.0;
   m_euler.euler(_angle,_x,_y,_z);
   updateGL();
 }
void GLWindow::setMatrixOrder (int _index) slot
called when the matrix order combobox is changed sets the new matrix order for m_matrixOrder and forces re-draw called from MainWindow
Parameters
[in] _index the index of the combobox
Definition at line 661 of file GLWindow.cpp.
References EULERTS, GIMBALLOCK, m_matrixOrder, RTS, TEULERS, and TRS.
 {
   switch(_index)
   {
     case 0 : { m_matrixOrder=GLWindow::RTS;   break; }
     case 1 : { m_matrixOrder=GLWindow::TRS;   break; }
     case 2 : { m_matrixOrder=GLWindow::GIMBALLOCK; break; }
     case 3 : { m_matrixOrder=GLWindow::EULERTS; break; }
     case 4 : { m_matrixOrder=GLWindow::TEULERS; break; }
     default : break;
   }
 updateGL();
 }
void GLWindow::setNormalSize (int _value) slot
slot to indicate the normal length slider had changed called from MainWindow
Parameters
[in] _value the new value of the tick box
Definition at line 610 of file GLWindow.cpp.
References m_normalSize.
 {
   m_normalSize=_value;
   updateGL();
 }
void GLWindow::setRotate (float _x, float _y, float _z) slot
called when any of the rotate elements are modified sets the new m_rotate matrix value and forces a re-calcuation and re-draw called from MainWindow
Parameters
[in] _x the value of rotation in the x
[in] _y the value of rotation in the y
[in] _z the value of rotation in the z
Definition at line 632 of file GLWindow.cpp.
References m_gimbal, and m_rotate.
 {
   ngl::Mat4 rx=1.0;
   ngl::Mat4 ry=1.0;
   ngl::Mat4 rz=1.0;
   rx.rotateX(_x);
   ry.rotateY(_y);
   rz.rotateZ(_z);
   m_rotate=rz*ry*rx;
   // now for the incorrect gimbal 1
   m_gimbal.identity();
   m_gimbal.rotateX(_x);
   m_gimbal.rotateY(_y);
   m_gimbal.rotateZ(_z);
   updateGL();
 }
void GLWindow::setScale (float _x, float _y, float _z) slot
called when any of the scale elements are modified sets the new m_scale matrix value and forces a re-calcuation and re-draw called from MainWindow
Parameters
[in] _x the value of scale in the x
[in] _y the value of scale in the y
[in] _z the value of scale in the z
Definition at line 616 of file GLWindow.cpp.
References m_scale.
 {
   m_scale.scale(_x,_y,_z);
   updateGL();
 }
void GLWindow::setScenePath (const std::string & _path) inline
Definition at line 70 of file GLWindow.h.
 { m_scenePath = _path; }
void GLWindow::setTranslate (float _x, float _y, float _z) slot
called when any of the translate elements are modified sets the new m_translate matrix value and forces a re-calcuation and re-draw called from MainWindow
Parameters
[in] _x the value of translate in the x
[in] _y the value of translate in the y
[in] _z the value of translate in the z
Definition at line 624 of file GLWindow.cpp.
References m_translate.
 {
   m_translate.translate(_x,_y,_z);
   updateGL();
 }
void GLWindow::toggleNormals (bool _value) slot
slot to indicate the normal tick box has been activated called from MainWindow
Parameters
[in] _value the new value of the tick box
Definition at line 588 of file GLWindow.cpp.
References m_drawNormals.
 {
   m_drawNormals=_value;
   updateGL();
 }
void GLWindow::toggleWireframe (bool _value) slot
slot to indicate the wireframe tick box has been activated called from MainWindow
Parameters
[in] _value the new value of the tick box
Definition at line 596 of file GLWindow.cpp.
 {
    if( _value == true)
    {
      glPolygonMode(GL_FRONT_AND_BACK,GL_LINE);
    }
    else
    {
      glPolygonMode(GL_FRONT_AND_BACK,GL_FILL);
    }
   updateGL();
 }
void GLWindow::vboChanged (int _index) slot
slot to indicate the vbo selection combo box has changed called from MainWindow
Parameters
[in] _index the new value of the combo box index
Definition at line 581 of file GLWindow.cpp.
References m_drawIndex.
 {
   m_drawIndex=_index;
   updateGL();
 }
void GLWindow::wheelEvent (QWheelEvent * _event) private
this method is called everytime the mouse wheel is moved inherited from QObject and overridden here.
Parameters
_event the Qt Event structure
Definition at line 558 of file GLWindow.cpp.
References m_cam.
 {
   float zoomScale = 0.0f;
   // check the diff of the wheel position (0 means no change)
   if(_event->delta() > 0)
   {
     zoomScale = -1.f;
     //m_modelPos.m_x+=ZOOM;
   }
   else if(_event->delta() <0 )
   {
     zoomScale =  1.f;
     //m_modelPos.m_x-=ZOOM;
   }
   m_cam->slide(0, 0, zoomScale);
   updateGL();
 }
Member Data Documentation
Axis* GLWindow::m_axis private
the axis
Definition at line 186 of file GLWindow.h.
ngl::Camera* GLWindow::m_cam
Our Camera.
Definition at line 75 of file GLWindow.h.
ngl::Colour GLWindow::m_colour private
the colour for the object material
Definition at line 178 of file GLWindow.h.
int GLWindow::m_drawIndex private
the index into the VBO name array for the drawing
Definition at line 141 of file GLWindow.h.
bool GLWindow::m_drawNormals private
flag to indicate if we draw the normals
Definition at line 145 of file GLWindow.h.
ngl::Mat4 GLWindow::m_euler private
the Euler rotation matrix
Definition at line 170 of file GLWindow.h.
GLuint GLWindow::m_fboID private
our FBO id used by the FBO
Definition at line 91 of file GLWindow.h.
ngl::Mat4 GLWindow::m_gimbal private
a matrix to demonstrate gimal locs
Definition at line 158 of file GLWindow.h.
ngl::Light* GLWindow::m_light private
the light for the shading
Definition at line 174 of file GLWindow.h.
ngl::Material GLWindow::m_material private
Definition at line 190 of file GLWindow.h.
MATRIXORDER GLWindow::m_matrixOrder private
the order of multiplication for the transform matrix
Definition at line 210 of file GLWindow.h.
ngl::Vec3 GLWindow::m_modelPos private
Definition at line 131 of file GLWindow.h.
ngl::Mat4 GLWindow::m_mouseGlobalTX private
used to store the global mouse transforms
Definition at line 136 of file GLWindow.h.
int GLWindow::m_normalSize private
the size to draw the normals
Definition at line 182 of file GLWindow.h.
int GLWindow::m_origX private
the previous x mouse value
Definition at line 116 of file GLWindow.h.
int GLWindow::m_origXPos private
the previous x mouse value for Position changes
Definition at line 124 of file GLWindow.h.
int GLWindow::m_origY private
the previous y mouse value
Definition at line 120 of file GLWindow.h.
int GLWindow::m_origYPos private
the previous y mouse value for Position changes
Definition at line 128 of file GLWindow.h.
GLuint GLWindow::m_rboID private
our render buffer id used by the FBO
Definition at line 95 of file GLWindow.h.
ngl::Mat4 GLWindow::m_rotate private
a matrix to hold the rotation
Definition at line 153 of file GLWindow.h.
bool GLWindow::m_rotateActive private
flag to indicate if the Left mouse button is pressed when dragging
Definition at line 108 of file GLWindow.h.
ngl::Mat4 GLWindow::m_scale private
the scale matrix
Definition at line 166 of file GLWindow.h.
Renderer::Scene* GLWindow::m_scene private
Definition at line 192 of file GLWindow.h.
std::string GLWindow::m_scenePath
Definition at line 68 of file GLWindow.h.
int GLWindow::m_spinXFace private
used to store the x rotation mouse value
Definition at line 100 of file GLWindow.h.
int GLWindow::m_spinYFace private
used to store the y rotation mouse value
Definition at line 104 of file GLWindow.h.
GLuint GLWindow::m_textureID private
our texture id used by the FBO
Definition at line 87 of file GLWindow.h.
ngl::Mat4 GLWindow::m_transform private
the final transform matrix
Definition at line 149 of file GLWindow.h.
ngl::Mat4 GLWindow::m_translate private
the translation matrix
Definition at line 162 of file GLWindow.h.
bool GLWindow::m_translateActive private
flag to indicate if the Right mouse button is pressed when dragging
Definition at line 112 of file GLWindow.h.
std::vector<ngl::Vec3> GLWindow::m_verts
Definition at line 66 of file GLWindow.h.
QFuture<void> GLWindow::renderThread
Definition at line 79 of file GLWindow.h.
const std::string GLWindow::s_vboNames static private
Initial value:
=
{
  "sphere",
  "cylinder",
  "cone",
  "disk",
  "plane",
  "torus",
  "teapot",
  "octahedron",
  "dodecahedron",
  "icosahedron",
  "tetrahedron",
  "football",
  "cube",
  "troll",
  "buddah",
  "dragon",
  "bunny"
}
static array of names used in the vbo drawing initialised in GLWindow.cpp
Definition at line 350 of file GLWindow.h.
ngl::VertexArrayObject* GLWindow::test_vao
Definition at line 77 of file GLWindow.h.
The documentation for this class was generated from the following files:
GLWindow.h
GLWindow.cpp