AffineTransform: MainWindow Class Reference
MainWindow Class Reference
our main UI window, created by MainWindow.ui and extended here
#include <MainWindow.h>
Public Member Functions
MainWindow (QWidget *parent=0)
~MainWindow ()
Private Slots
void renderNow ()
void setScale ()
void setTranslate ()
void setRotate ()
void reset ()
void updateMatrix (ngl::Mat4 _m)
void setMatrix ()
void changeColour ()
void setEuler ()
void setTab (int _value)
void on_renderButton_clicked ()
void on_tabWidget_2_currentChanged (int index)
void on_tabWidget_currentChanged (int index)
void on_rendersamplesEdit_editingFinished ()
void on_renderHeightEdit_editingFinished ()
void on_renderWidthEdit_editingFinished ()
void on_renderFilenameEdit_editingFinished ()
void on_openScene_clicked ()
void on_quit_clicked ()
Private Member Functions
void keyPressEvent (QKeyEvent *_event)
override the keyPressEvent inherited from QObject so we can handle key presses.
Private Attributes
Ui::MainWindow * m_ui
GLWindow * m_gl
Renderer::Scene * m_scene
Detailed Description
our main UI window, created by MainWindow.ui and extended here
Definition at line 25 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0) explicit
connect the vboSelection combo to the index value in the gl window class
connect the normal and vertexx tick boxes
connect the wireframe tick box
connect the reset button
Definition at line 10 of file MainWindow.cpp.
References m_gl, m_ui, on_openScene_clicked(), on_quit_clicked(), renderNow(), and updateMatrix().
   : QMainWindow(parent), m_ui(new Ui::MainWindow), m_scene(NULL)
 {
   // setup the user interface
   m_ui->setupUi(this);
   // now we create our glwindow class
   // create an openGL format and pass to the new GLWidget
   QGLFormat format;
   format.setVersion(3,2);
   format.setProfile( QGLFormat::CoreProfile);
   m_ui->tabWidget->setCurrentIndex(0);
   m_gl = new GLWindow(format,this);
   m_ui->horizontalLayout_7->addWidget(m_gl);
 //  auto* a = new GLWindow(format, this);
 //  m_ui->horizontalLayout_6->addWidget(a);
   //connect(m_ui->renderButton, SIGNAL(clicked()), this, SLOT(renderNow()));
   // the following code connects the ui components to the GL class
   //connect(m_ui->m_vboSelection,SIGNAL(currentIndexChanged(int)),m_gl,SLOT(vboChanged(int )));
   //connect(m_ui->m_normals,SIGNAL(toggled(bool)),m_gl,SLOT(toggleNormals(bool)));
   //connect(m_ui->m_wireframe,SIGNAL(toggled(bool)),m_gl,SLOT(toggleWireframe(bool)));
 //  connect(m_ui->m_sx,SIGNAL(valueChanged(double)),this,SLOT(setScale()));
 //  connect(m_ui->m_sy,SIGNAL(valueChanged(double)),this,SLOT(setScale()));
 //  connect(m_ui->m_sz,SIGNAL(valueChanged(double)),this,SLOT(setScale()));
 //  connect(m_ui->m_tx,SIGNAL(valueChanged(double)),this,SLOT(setTranslate()));
 //  connect(m_ui->m_ty,SIGNAL(valueChanged(double)),this,SLOT(setTranslate()));
 //  connect(m_ui->m_tz,SIGNAL(valueChanged(double)),this,SLOT(setTranslate()));
 //  connect(m_ui->m_rx,SIGNAL(valueChanged(double)),this,SLOT(setRotate()));
 //  connect(m_ui->m_ry,SIGNAL(valueChanged(double)),this,SLOT(setRotate()));
 //  connect(m_ui->m_rz,SIGNAL(valueChanged(double)),this,SLOT(setRotate()));
   //connect(m_ui->m_reset,SIGNAL(clicked()),this,SLOT(reset()));
   // connect the emit matrix dirty to update the matrix.
   connect(m_gl,SIGNAL(matrixDirty(ngl::Mat4)),this,SLOT(updateMatrix(ngl::Mat4)));
   connect(m_ui->actionRender, SIGNAL(triggered()), this, SLOT(renderNow()) );
   connect(m_ui->actionOpen_scene, SIGNAL(triggered()), this, SLOT(on_openScene_clicked()) );
   connect(m_ui->actionQuit, SIGNAL(triggered()), this, SLOT(on_quit_clicked()) );
   connect(m_ui->renderButton, SIGNAL(triggered()), this, SLOT(renderNow()) );
   // connect the slider to the normal drawing attrib size
   //connect(m_ui->m_normalSize,SIGNAL(valueChanged(int)),m_gl,SLOT(setNormalSize(int)));
   /*
   // now connect the matrix spin wheels with the set matrix command
   connect(m_ui->m_m00,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m01,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m02,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m03,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m10,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m11,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m12,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m13,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m20,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m21,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m22,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m23,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m30,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m31,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m32,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   connect(m_ui->m_m33,SIGNAL(valueChanged(double)),this,SLOT(setMatrix()));
   */
   //connect(m_ui->m_colour,SIGNAL(clicked()),this,SLOT(changeColour()));
 //  connect(m_ui->m_matrixOrder,SIGNAL(currentIndexChanged(int)),m_gl,SLOT(setMatrixOrder(int)));
 //  connect(m_ui->m_matrixOrder,SIGNAL(currentIndexChanged(int)),this,SLOT(setTab(int)));
 //  connect(m_ui->m_eulerAngle,SIGNAL(valueChanged(double)),this,SLOT(setEuler()));
 //  connect(m_ui->m_eulerXAxis,SIGNAL(valueChanged(double)),this,SLOT(setEuler()));
 //  connect(m_ui->m_eulerYAxis,SIGNAL(valueChanged(double)),this,SLOT(setEuler()));
 //  connect(m_ui->m_eulerZAxis,SIGNAL(valueChanged(double)),this,SLOT(setEuler()));
 }
MainWindow::~MainWindow ()
Definition at line 89 of file MainWindow.cpp.
References m_ui.
 {
     delete m_ui;
 }
Member Function Documentation
void MainWindow::changeColour () private slot
Definition at line 215 of file MainWindow.cpp.
References m_gl, and GLWindow::setColour().
 {
   // this slot is called when the colour button is pushed
   // we first use the colour dialog to get the colour
   QColor colour = QColorDialog::getColor();
   // we now check to see if a colour was set or if the cancel was pressed
   // using the isValid method
   if (colour.isValid())
   {
     // if it was we get the colour values using the ..F() function and call the
     // SetColour method in the GLWindow
     m_gl->setColour(colour.redF(),colour.greenF(),colour.blueF());
     // finally we update the GLWindow.
     m_gl->updateGL();
   }
 }
void MainWindow::keyPressEvent (QKeyEvent * _event) private
override the keyPressEvent inherited from QObject so we can handle key presses.
Parameters
[in] _event the event to process
Definition at line 174 of file MainWindow.cpp.
References m_gl, and renderNow().
 {
   this->setFocus(Qt::ActiveWindowFocusReason);
   float increment=0.1;
   if ( QApplication::keyboardModifiers ()  == Qt::ShiftModifier)
   {
     increment=-0.1;
   }
   // this method is called every time the main window recives a key event.
   // we then switch on the key value and set the camera in the GLWindow
   switch (_event->key())
   {
     case Qt::Key_Escape :{ QApplication::exit(EXIT_SUCCESS); break;}
     case Qt::Key_R :
     {
         if ( QApplication::keyboardModifiers ()  == Qt::ControlModifier)
         {
             renderNow();
         }
         break;
     }
 //  case Qt::Key_X : { m_ui->m_rx->setValue(m_ui->m_rx->value()+increment*10); break; }
 //  case Qt::Key_Y : { m_ui->m_ry->setValue(m_ui->m_ry->value()+increment*10); break; }
 //  case Qt::Key_Z : { m_ui->m_rz->setValue(m_ui->m_rz->value()+increment*10); break; }
 //  case Qt::Key_I : { m_ui->m_ty->setValue(m_ui->m_ty->value()+increment); break; }
 //  case Qt::Key_M : { m_ui->m_ty->setValue(m_ui->m_ty->value()-increment); break; }
 //  case Qt::Key_J : { m_ui->m_tx->setValue(m_ui->m_tx->value()-increment); break; }
 //  case Qt::Key_K : { m_ui->m_tx->setValue(m_ui->m_tx->value()+increment); break; }
 //  case Qt::Key_O : { m_ui->m_tz->setValue(m_ui->m_tz->value()-increment); break; }
 //  case Qt::Key_L : { m_ui->m_tz->setValue(m_ui->m_tz->value()+increment); break; }
     default : break;
   }
   // finally update the GLWindow and re-draw
   m_gl->updateGL();
 }
void MainWindow::on_openScene_clicked () private slot
Definition at line 310 of file MainWindow.cpp.
References m_gl, and GLWindow::setScenePath().
 {
   QString path = QFileDialog::getOpenFileName(this, "Open scene", ".", tr("T-ray Scene (*.txt *.tray);;"));
   if ( path.isNull() == false )
   {
       m_gl->setScenePath(path.toStdString());
   }
 }
void MainWindow::on_quit_clicked () private slot
Definition at line 319 of file MainWindow.cpp.
 {
   QApplication::exit(EXIT_SUCCESS);
 }
void MainWindow::on_renderButton_clicked () private slot
Definition at line 257 of file MainWindow.cpp.
References renderNow().
 {
     renderNow();
 }
void MainWindow::on_renderFilenameEdit_editingFinished () private slot
Definition at line 305 of file MainWindow.cpp.
 {
 }
void MainWindow::on_renderHeightEdit_editingFinished () private slot
Definition at line 285 of file MainWindow.cpp.
References m_ui.
 {
     int val = m_ui->renderHeightEdit->text().toInt();
     qDebug("%d", val);
     if(val <= 0)
       m_ui->renderHeightEdit->setText("1");
 }
void MainWindow::on_rendersamplesEdit_editingFinished () private slot
Definition at line 275 of file MainWindow.cpp.
References m_ui.
 {
     int val = m_ui->rendersamplesEdit->text().toInt();
     qDebug("%d", val);
     if(val <= 0)
       m_ui->rendersamplesEdit->setText("1");
 }
void MainWindow::on_renderWidthEdit_editingFinished () private slot
Definition at line 295 of file MainWindow.cpp.
References m_ui.
 {
   int val = m_ui->renderWidthEdit->text().toInt();
   qDebug("%d", val);
   if(val <= 0)
     m_ui->renderWidthEdit->setText("1");
 }
void MainWindow::on_tabWidget_2_currentChanged (int index) private slot
Definition at line 262 of file MainWindow.cpp.
 {
 //    m_ui->tabWidget->setCurrentIndex(index);
 //    m_ui->tabWidget_2->setCurrentIndex(index);
 }
void MainWindow::on_tabWidget_currentChanged (int index) private slot
Definition at line 268 of file MainWindow.cpp.
 {
 //    m_ui->tabWidget->setCurrentIndex(index);
 //    m_ui->tabWidget_2->setCurrentIndex(index);
 }
void MainWindow::renderNow () private slot
Definition at line 94 of file MainWindow.cpp.
References GLWindow::getScene(), m_gl, m_ui, and GLWindow::renderScene().
 {
   Renderer::RenderContext* context = new Renderer::RenderContext(m_gl->getScene(),
                                                                  NULL,
                                                                  m_ui->renderWidthEdit->text().toInt(),
                                                                  m_ui->renderHeightEdit->text().toInt(),
                                                                  m_ui->rendersamplesEdit->text().toInt(),
                                                                  m_ui->renderFilenameEdit->text().toStdString());
   m_gl->renderScene(context);
 }
void MainWindow::reset () private slot
Definition at line 125 of file MainWindow.cpp.
References m_gl, and GLWindow::resetMouse().
 {
   //m_ui->m_rx->setValue(0.0);
 //  m_ui->m_ry->setValue(0.0);
 //  m_ui->m_rz->setValue(0.0);
 //  m_ui->m_sx->setValue(1.0);
 //  m_ui->m_sy->setValue(1.0);
 //  m_ui->m_sz->setValue(1.0);
 //  m_ui->m_tx->setValue(0.0);
 //  m_ui->m_ty->setValue(0.0);
 //  m_ui->m_tz->setValue(0.0);
   //m_ui->m_normals->setChecked(false);
   //m_ui->m_wireframe->setChecked(false);
   m_gl->resetMouse();
 }
void MainWindow::setEuler () private slot
Definition at line 235 of file MainWindow.cpp.
 {
 //  m_gl->setEuler(m_ui->m_eulerAngle->value(),
 //                 m_ui->m_eulerXAxis->value(),
 //                 m_ui->m_eulerYAxis->value(),
 //                 m_ui->m_eulerZAxis->value());
 }
void MainWindow::setMatrix () private slot
Definition at line 168 of file MainWindow.cpp.
 {
 }
void MainWindow::setRotate () private slot
Definition at line 119 of file MainWindow.cpp.
 {
   //m_gl->setRotate(m_ui->m_rx->value(), m_ui->m_ry->value(),m_ui->m_rz->value());
 }
void MainWindow::setScale () private slot
Definition at line 107 of file MainWindow.cpp.
 {
   //m_gl->setScale(m_ui->m_sx->value(), m_ui->m_sy->value(),m_ui->m_sz->value());
 }
void MainWindow::setTab (int _value) private slot
Definition at line 244 of file MainWindow.cpp.
 {
   if(_value >2)
   {
 //    m_ui->s_rotateTabWidget->setCurrentIndex(1);
   }
   else
   {
 //    m_ui->s_rotateTabWidget->setCurrentIndex(0);
   }
 }
void MainWindow::setTranslate () private slot
Definition at line 113 of file MainWindow.cpp.
 {
   //m_gl->setTranslate(m_ui->m_tx->value(), m_ui->m_ty->value(),m_ui->m_tz->value());
 }
void MainWindow::updateMatrix (ngl::Mat4 _m) private slot
Definition at line 142 of file MainWindow.cpp.
 {
   ngl::Real *data=_m.openGL();
 //  m_ui->m_m00->setValue(data[0]);
   //m_ui->m_m10->setValue(data[1]);
   //m_ui->m_m20->setValue(data[2]);
   //m_ui->m_m30->setValue(data[3]);
   //m_ui->m_m01->setValue(data[4]);
   //m_ui->m_m11->setValue(data[5]);
   //m_ui->m_m21->setValue(data[6]);
   //m_ui->m_m31->setValue(data[7]);
   //m_ui->m_m02->setValue(data[8]);
   //m_ui->m_m12->setValue(data[9]);
   //m_ui->m_m22->setValue(data[10]);
   //m_ui->m_m32->setValue(data[11]);
   //m_ui->m_m03->setValue(data[12]);
   //m_ui->m_m13->setValue(data[13]);
   //m_ui->m_m23->setValue(data[14]);
   //m_ui->m_m33->setValue(data[15]);
 }
Member Data Documentation
GLWindow* MainWindow::m_gl private
Definition at line 43 of file MainWindow.h.
Renderer::Scene* MainWindow::m_scene private
Definition at line 46 of file MainWindow.h.
Ui::MainWindow* MainWindow::m_ui private
Definition at line 40 of file MainWindow.h.
The documentation for this class was generated from the following files:
MainWindow.h
MainWindow.cpp