AffineTransform: Renderer::Sphere Class Reference
Renderer::Sphere Class Reference
The Sphere class represents a sphere defined by a radius and transform.
#include <sphere.h>
Public Member Functions
Sphere (const ngl::Mat4 &_toWorldSpace, const Material &_material, float _radius=1.0f)
Sphere ctor.
virtual bool intersect (const Ray &_ray, HitData &_hit) const
intersect samples all the objects in the scene to figure out if the ray intersects
virtual void draw () const
draws the primitive in the 3d visualisation
virtual ngl::Vec3 sample () const
samples a point on the surface, used for lighting
virtual ngl::Vec3 getNormal (ngl::Vec3 _point) const
getNormal calculates the surface normal a certain point
ngl::Vec3 tangentSphere (const ngl::Vec3 _point, const ngl::Vec3 _direction) const
Public Member Functions inherited from Renderer::Primitive
Primitive (const ngl::Mat4 &_toWorldSpace, const Material &_material)
Primitive constructs the to world and to object transform matrices.
virtual ~Primitive ()
Ray rayToObjectSpace (const Ray &_ray) const
rayToObjectSpace converts _ray to this primitive's object space
Ray rayToWorldSpace (const Ray &_ray) const
rayToWorldSpace converts _ray to this primitive's world space
Material getSurfaceMaterial () const
getSurfaceMaterial
const ngl::Mat4 & objectTransform () const
objectTransform
const ngl::Mat4 & worldTransform () const
worldTransform
Private Attributes
float m_radius
float m_squaredRadius
Additional Inherited Members
Protected Attributes inherited from Renderer::Primitive
ngl::Mat4 m_toWorldSpace
m_toWorldSpace stores the object space to world space transformation matrix for this primitive.
ngl::Mat4 m_toObjectSpace
m_toObjectSpace stores the world space to object space transformation matrix for this primitive.
Material m_material
Detailed Description
The Sphere class represents a sphere defined by a radius and transform.
Definition at line 12 of file sphere.h.
Constructor & Destructor Documentation
Renderer::Sphere::Sphere (const ngl::Mat4 & _toWorldSpace, const Material & _material, float _radius = 1.0f) inline
Sphere ctor.
Parameters
_toWorldSpace
_material
_radius
Definition at line 21 of file sphere.h.
         : Primitive(_toWorldSpace, _material), m_radius(_radius), m_squaredRadius(_radius * _radius)
     {;}
Member Function Documentation
void Renderer::Sphere::draw () const virtual
draws the primitive in the 3d visualisation
Implements Renderer::Primitive.
Definition at line 89 of file sphere.cpp.
 {
     //glCullFace(GL_FRONT);
     ngl::VAOPrimitives *prim=ngl::VAOPrimitives::instance();
     prim->draw("sphere");
     //glCullFace(GL_BACK);
 }
ngl::Vec3 Renderer::Sphere::getNormal (ngl::Vec3 _point) const virtual
getNormal calculates the surface normal a certain point
Parameters
_point a point on the surface
Returns
the normal on the surface at _point
Implements Renderer::Primitive.
Definition at line 18 of file sphere.cpp.
References Renderer::Primitive::m_toObjectSpace, and transformPosition().
 {
     ngl::Vec3 origin = transformPosition( ngl::Vec3(), m_toObjectSpace);
     ngl::Vec3 dir(_point - origin);
     dir.normalize();
     return dir;
 }
bool Renderer::Sphere::intersect (const Ray & _ray, HitData & _hit) const virtual
intersect samples all the objects in the scene to figure out if the ray intersects
Parameters
_ray expects a ray in worldspace
_hit is filled with data if there is a collision, otherwise it is not
Returns
true if there is a collision, false if not
Implements Renderer::Primitive.
Definition at line 28 of file sphere.cpp.
References Renderer::EPSILON, getNormal(), Renderer::Ray::m_direction, Renderer::HitData::m_object, Renderer::Ray::m_origin, Renderer::HitData::m_ray, m_squaredRadius, Renderer::HitData::m_surfaceImpact, Renderer::HitData::m_surfaceNormal, Renderer::HitData::m_t, Renderer::HitData::m_u, Renderer::HitData::m_v, Renderer::HitData::m_w, and SolveQuadratic().
 {
     const ngl::Vec3 rayDirection = _ray.m_direction;
     const ngl::Vec3 rayOrigin = _ray.m_origin;
     const float a = rayDirection.dot(rayDirection);
     const float b = rayDirection.dot(rayOrigin) * 2.0f;
     const float c = rayOrigin.dot(rayOrigin) - m_squaredRadius;
     float t0 = -1.f, t1 = -1.f;
     if(!SolveQuadratic(a,b,c, t0, t1) || t1 < EPSILON)
     {
         // No valid intersections
         // (we didn't touch the sphere or the intersection was inside)
         return false;
     }
 //     t1 is expected to be further away
     if(t1 < t0)
     {
         std::swap(t0, t1);
     }
     // Choose the closest intersection
     _hit.m_t = (t0 < 0) ? t1 : t0;
     _hit.m_surfaceImpact = _ray(_hit.m_t);
     _hit.m_surfaceNormal = getNormal(_hit.m_surfaceImpact);
     //Generate UVs (http://www.mvps.org/directx/articles/spheremap.htm)
     _hit.m_u = asinf(_hit.m_surfaceNormal.m_x)/M_PI + 0.5;
     _hit.m_v = asinf(_hit.m_surfaceNormal.m_y)/M_PI + 0.5;
     _hit.m_w = 1 - _hit.m_u - _hit.m_v;
     _hit.m_ray = _ray;
     _hit.m_object = this;
     return true;
 }
ngl::Vec3 Renderer::Sphere::sample () const virtual
samples a point on the surface, used for lighting
Returns
a point on the primitive surface
Implements Renderer::Primitive.
Definition at line 68 of file sphere.cpp.
References m_radius, Renderer::Primitive::m_toObjectSpace, and transformPosition().
 {
     ngl::Vec3 center = transformPosition( ngl::Vec3(), m_toObjectSpace);
     float r1 = drand48();
     float r2 = drand48();
     ngl::Vec3 point( center.m_x + 2 * m_radius * cos(2 * M_PI * r1) * sqrt(r2 * (1 - r2)),
                       center.m_y + 2 * m_radius * sin(2 * M_PI * r1) * sqrt(r2 * (1 - r2)),
                       center.m_z + m_radius * (1 - (2*r2))
                 );
     return point;
 }
ngl::Vec3 Renderer::Sphere::tangentSphere (const ngl::Vec3 _point, const ngl::Vec3 _direction) const
Definition at line 82 of file sphere.cpp.
References getNormal().
 {
     float t = getNormal(_point).dot(_direction);
     return (t >= 0) ? t : 0;
 }
Member Data Documentation
float Renderer::Sphere::m_radius private
Definition at line 37 of file sphere.h.
float Renderer::Sphere::m_squaredRadius private
Definition at line 38 of file sphere.h.
The documentation for this class was generated from the following files:
sphere.h
sphere.cpp