AffineTransform: Renderer::Primitive Class Reference
Renderer::Primitive Class Reference abstract
The Primitive class is the abstract class representing a renderer primitive, the intersect and draw methods must be overloaded in child classes.
#include <primitive.h>
Public Member Functions
Primitive (const ngl::Mat4 &_toWorldSpace, const Material &_material)
Primitive constructs the to world and to object transform matrices.
virtual ~Primitive ()
virtual bool intersect (const Ray &_ray, HitData &_hit) const =0
intersect samples all the objects in the scene to figure out if the ray intersects
virtual void draw () const =0
draws the primitive in the 3d visualisation
virtual ngl::Vec3 sample () const =0
samples a point on the surface, used for lighting
virtual ngl::Vec3 getNormal (ngl::Vec3 _point) const =0
getNormal calculates the surface normal a certain point
Ray rayToObjectSpace (const Ray &_ray) const
rayToObjectSpace converts _ray to this primitive's object space
Ray rayToWorldSpace (const Ray &_ray) const
rayToWorldSpace converts _ray to this primitive's world space
Material getSurfaceMaterial () const
getSurfaceMaterial
const ngl::Mat4 & objectTransform () const
objectTransform
const ngl::Mat4 & worldTransform () const
worldTransform
Protected Attributes
ngl::Mat4 m_toWorldSpace
m_toWorldSpace stores the object space to world space transformation matrix for this primitive.
ngl::Mat4 m_toObjectSpace
m_toObjectSpace stores the world space to object space transformation matrix for this primitive.
Material m_material
Detailed Description
The Primitive class is the abstract class representing a renderer primitive, the intersect and draw methods must be overloaded in child classes.
Definition at line 39 of file primitive.h.
Constructor & Destructor Documentation
Renderer::Primitive::Primitive (const ngl::Mat4 & _toWorldSpace, const Material & _material)
Primitive constructs the to world and to object transform matrices.
Parameters
_toWorldSpace
_material
Definition at line 19 of file primitive.cpp.
References m_toObjectSpace, and m_toWorldSpace.
     : m_toWorldSpace(_toWorldSpace), m_material(_material)
 {
   m_toObjectSpace = m_toWorldSpace.inverse();
 }
virtual Renderer::Primitive::~Primitive () inline virtual
Definition at line 49 of file primitive.h.
 {;}
Member Function Documentation
virtual void Renderer::Primitive::draw () const pure virtual
draws the primitive in the 3d visualisation
Implemented in Renderer::Triangle, Renderer::Sphere, and Renderer::Plane.
virtual ngl::Vec3 Renderer::Primitive::getNormal (ngl::Vec3 _point) const pure virtual
getNormal calculates the surface normal a certain point
Parameters
_point a point on the surface
Returns
the normal on the surface at _point
Implemented in Renderer::Triangle, Renderer::Sphere, and Renderer::Plane.
Material Renderer::Primitive::getSurfaceMaterial () const inline
getSurfaceMaterial
Returns
the primitive's surface material
Definition at line 95 of file primitive.h.
References m_material.
 { return m_material; }
virtual bool Renderer::Primitive::intersect (const Ray & _ray, HitData & _hit) const pure virtual
intersect samples all the objects in the scene to figure out if the ray intersects
Parameters
_ray expects a ray in worldspace
_hit is filled with data if there is a collision, otherwise it is not
Returns
true if there is a collision, false if not
Implemented in Renderer::Triangle, Renderer::Sphere, and Renderer::Plane.
const ngl::Mat4& Renderer::Primitive::objectTransform () const inline
objectTransform
Returns
the primitive's object space transform matrix
Definition at line 101 of file primitive.h.
References m_toObjectSpace.
 { return m_toObjectSpace; }
Ray Renderer::Primitive::rayToObjectSpace (const Ray & _ray) const
rayToObjectSpace converts _ray to this primitive's object space
Primitive::rayToObjectSpace.
Parameters
_ray
Returns
the transformed ray
Parameters
_ray
Returns
Definition at line 31 of file primitive.cpp.
References Renderer::Ray::m_direction, Renderer::Ray::m_origin, Renderer::Ray::m_tmax, Renderer::Ray::m_tmin, m_toObjectSpace, Renderer::Ray::m_type, transformNormal(), and transformPosition().
 {
     /* To get correct object intersections the ray must also be transformed
      * to match the primitive's transform/scale.
      *
      * The primitive is transformed in world space, but as the ray is already in world space
      * it must be transformed by the inverse (object space) to match the primitive's transforms.
      */
     ngl::Vec3 rayOrigin = transformPosition(_ray.m_origin, m_toObjectSpace);
     ngl::Vec3 rayDirection = transformNormal(_ray.m_direction , m_toObjectSpace);
 //    ngl::Mat4 tmp = m_toObjectSpace;
 //    tmp.transpose();
 //    ngl::Vec3 rayOrigin = ngl::Vec4( tmp * ngl::Vec4(_ray.m_origin)).toVec3();;
 //    ngl::Vec3 rayDirection = ngl::Vec4( m_toObjectSpace * ngl::Vec4(_ray.m_direction)).toVec3(); // Apply world transforms to ray direction
 //    //rayOrigin.normalize();
 //    rayDirection.normalize();
     return Ray(rayOrigin, rayDirection, _ray.m_type, _ray.m_tmin, _ray.m_tmax);
 }
Ray Renderer::Primitive::rayToWorldSpace (const Ray & _ray) const
rayToWorldSpace converts _ray to this primitive's world space
Primitive::rayToWorldSpace.
Parameters
_ray
Returns
the transformed ray
Parameters
_ray
Returns
Definition at line 59 of file primitive.cpp.
References Renderer::Ray::m_direction, Renderer::Ray::m_origin, Renderer::Ray::m_tmax, Renderer::Ray::m_tmin, m_toWorldSpace, Renderer::Ray::m_type, transformNormal(), and transformPosition().
 {
     /* To get correct object intersections the ray must also be transformed
      * to match the primitive's transform/scale.
      *
      * The primitive is transformed in world space, but as the ray is already in world space
      * it must be transformed by the inverse (object space) to match the primitive's transforms.
      */
     ngl::Vec3 rayOrigin = transformPosition(_ray.m_origin, m_toWorldSpace);
     ngl::Vec3 rayDirection = transformNormal(_ray.m_direction , m_toWorldSpace);
 //    ngl::Mat4 tmp = m_toWorldSpace;
 //    tmp.transpose();
 //    ngl::Vec3 rayOrigin = ngl::Vec4( tmp * ngl::Vec4(_ray.m_origin)).toVec3();;
 //    ngl::Vec3 rayDirection = ngl::Vec4( m_toWorldSpace * ngl::Vec4(_ray.m_direction)).toVec3(); // Apply world transforms to ray direction
     //rayOrigin.normalize();
 //    rayDirection.normalize();
     return Ray(rayOrigin, rayDirection, _ray.m_type, _ray.m_tmin, _ray.m_tmax);
 }
virtual ngl::Vec3 Renderer::Primitive::sample () const pure virtual
samples a point on the surface, used for lighting
Returns
a point on the primitive surface
Implemented in Renderer::Triangle, Renderer::Sphere, and Renderer::Plane.
const ngl::Mat4& Renderer::Primitive::worldTransform () const inline
worldTransform
Returns
the primitive's object worldtransform matrix
Definition at line 107 of file primitive.h.
References m_toWorldSpace.
 { return m_toWorldSpace; }
Member Data Documentation
Material Renderer::Primitive::m_material protected
Definition at line 122 of file primitive.h.
ngl::Mat4 Renderer::Primitive::m_toObjectSpace protected
m_toObjectSpace stores the world space to object space transformation matrix for this primitive.
Definition at line 120 of file primitive.h.
ngl::Mat4 Renderer::Primitive::m_toWorldSpace protected
m_toWorldSpace stores the object space to world space transformation matrix for this primitive.
Definition at line 115 of file primitive.h.
The documentation for this class was generated from the following files:
primitive.h
primitive.cpp