AffineTransform: Renderer::Camera Class Reference
Renderer::Camera Class Reference
The Camera class encapsulates just the render camera, providing methods to calculate FOV, clipping planes and world/object space transform matrices.
#include <camera.h>
Public Member Functions
Camera (const ngl::Mat4 &_toWorldSpace=ngl::Mat4(), float _fov=45.f, float _nearClip=0.1f, float _farClip=1000.f)
void setFOV (float _fov)
void setClippingPlanes (float _near, float _far)
void setCameraWorldSpace (const ngl::Mat4 &_toWorldSpace)
const ngl::Mat4 & getObjectSpaceMatrix () const
const ngl::Mat4 & getWorldSpaceMatrix () const
float getFOV () const
float getAngle () const
float getNearClipPlane () const
float getfarClipPlane () const
Private Attributes
ngl::Mat4 m_toObjectSpace
ngl::Mat4 m_toWorldSpace
float m_nearClippingPlane
float m_farClippingPlane
float m_fov
float m_angle
m_angle is used to compute cameraspace rays
Detailed Description
The Camera class encapsulates just the render camera, providing methods to calculate FOV, clipping planes and world/object space transform matrices.
Definition at line 14 of file camera.h.
Constructor & Destructor Documentation
Renderer::Camera::Camera (const ngl::Mat4 & _toWorldSpace = ngl::Mat4(), float _fov = 45.f, float _nearClip = 0.1f, float _farClip = 1000.f)
Definition at line 8 of file camera.cpp.
References setCameraWorldSpace(), setClippingPlanes(), and setFOV().
 {
     setFOV(_fov);
     setClippingPlanes(_nearClip, _farClip);
     setCameraWorldSpace(_toWorldSpace);
     if( _toWorldSpace.m_00 != 1.0f
      || _toWorldSpace.m_11 != 1.0f
      || _toWorldSpace.m_22 != 1.0f)
     {
         qWarning() << "Render camera scale is not 1";
     }
 }
Member Function Documentation
float Renderer::Camera::getAngle () const inline
Definition at line 70 of file camera.h.
References m_angle.
 { return m_angle; }
float Renderer::Camera::getfarClipPlane () const inline
Definition at line 73 of file camera.h.
References m_farClippingPlane.
 { return m_farClippingPlane; }
float Renderer::Camera::getFOV () const inline
Definition at line 69 of file camera.h.
References m_fov.
 { return m_fov; }
float Renderer::Camera::getNearClipPlane () const inline
Definition at line 72 of file camera.h.
References m_nearClippingPlane.
 { return m_nearClippingPlane; }
const ngl::Mat4& Renderer::Camera::getObjectSpaceMatrix () const inline
Definition at line 65 of file camera.h.
References m_toObjectSpace.
 { return m_toObjectSpace; }
const ngl::Mat4& Renderer::Camera::getWorldSpaceMatrix () const inline
Definition at line 67 of file camera.h.
References m_toWorldSpace.
 { return m_toWorldSpace; }
void Renderer::Camera::setCameraWorldSpace (const ngl::Mat4 & _toWorldSpace) inline
Definition at line 54 of file camera.h.
References m_toObjectSpace, and m_toWorldSpace.
     {
         ngl::Mat4 inverseWorldSpace = _toWorldSpace; // Make a non-const copy
         m_toWorldSpace = _toWorldSpace;
         m_toObjectSpace = inverseWorldSpace.inverse();
     }
void Renderer::Camera::setClippingPlanes (float _near, float _far) inline
Definition at line 48 of file camera.h.
References m_farClippingPlane, and m_nearClippingPlane.
     {
         m_nearClippingPlane = _near;
         m_farClippingPlane = _far;
     }
void Renderer::Camera::setFOV (float _fov) inline
Definition at line 26 of file camera.h.
References degreesToRadians(), m_angle, and m_fov.
     {
         m_fov = _fov;
         /*                C
          *
          *               /|
          *              / |
          *             /  |
          *            /   |
          *           /    | 1 (screenheight is between 1 and -1)
          *          /     |
          *         /\     |
          *      A /α_\____| B
          *            1
          *
          * m_angle = α = atan(opp/adj) = atan(1/1)
          */
         m_angle = atan( degreesToRadians(m_fov * 0.5) ); // Necessary to remap the [1:-1] screenspace ratio onto the aspect ratio, into camera space
     }
Member Data Documentation
float Renderer::Camera::m_angle private
m_angle is used to compute cameraspace rays
Definition at line 86 of file camera.h.
float Renderer::Camera::m_farClippingPlane private
Definition at line 80 of file camera.h.
float Renderer::Camera::m_fov private
Definition at line 81 of file camera.h.
float Renderer::Camera::m_nearClippingPlane private
Definition at line 79 of file camera.h.
ngl::Mat4 Renderer::Camera::m_toObjectSpace private
Definition at line 76 of file camera.h.
ngl::Mat4 Renderer::Camera::m_toWorldSpace private
Definition at line 77 of file camera.h.
The documentation for this class was generated from the following files:
camera.h
camera.cpp