AffineTransform: Renderer Namespace Reference
Renderer Namespace Reference
Classes
class Camera
The Camera class encapsulates just the render camera, providing methods to calculate FOV, clipping planes and world/object space transform matrices.
struct HitData
The HitData structure is passed around during the rendering process, storing important hit data required by all parts of the pipeline.
class Plane
class Primitive
The Primitive class is the abstract class representing a renderer primitive, the intersect and draw methods must be overloaded in child classes.
struct Ray
The Ray struct represents a direction starting from an origin point, it used as a camera, shadow, reflection and refraction ray depending on the space it is currently transformed to.
struct RenderContext
The RendererContext class is a convenience class that allows us to pass around scene information.
class Scene
The Scene class represents the 3D world, mainly storing data about the object primitives.
class SceneFile
The SceneFile class parses a text file for scene information and constructs a new scene from it.
class Sphere
The Sphere class represents a sphere defined by a radius and transform.
class Triangle
The Triangle class represents a triangle with 3 vertices and a transform.
Functions
Image::Pixel shade (RenderContext *_context)
shade checks if the last ray intersection is shaded by another object or has a clear path to a light source
Image::Pixel trace (const Ray &_ray, RenderContext *_context)
trace checks if _ray intersects with anything in the scene
void render (RenderContext *_context)
render starts the tracing process, setting up canonical camera space rays and firing them into the scene
template<typename T >
T popFirstItem (std::deque< T > &_items)
Variables
const double EPSILON = 1.0e-6
Function Documentation
template<typename T > T Renderer::popFirstItem (std::deque< T > & _items)
Bug:
Too late to fix now, but data is read in the incorrect order. Would explain why models were facing the wrong way, as xyz is imported as zyx
Definition at line 15 of file scenefile.cpp.
 {
     T item = _items.front();
     _items.pop_front();
     return item;
 }
void Renderer::render (RenderContext * _context)
render starts the tracing process, setting up canonical camera space rays and firing them into the scene
Parameters
_context stores scene information that needs to be passed between all parts of the pipeline
Todo:
Add a better sampler (stratified?), move into Sampler class, put in render context https://www.cs.duke.edu/courses/spring09/cps111/notes/sampling.pdf
Definition at line 171 of file renderer.cpp.
References Renderer::Ray::CAMERA, Renderer::Camera::getAngle(), Renderer::Camera::getfarClipPlane(), Renderer::Camera::getNearClipPlane(), Renderer::Camera::getWorldSpaceMatrix(), Renderer::RenderContext::m_aspectRatio, Renderer::RenderContext::m_depth, Renderer::RenderContext::m_imageHeight, Renderer::RenderContext::m_imageWidth, Renderer::RenderContext::m_outputPath, Renderer::RenderContext::m_renderCamera, Renderer::RenderContext::m_samples, ImagePPM::save(), Image::setPixel(), and trace().
   {
     ImagePPM image(_context->m_imageWidth, _context->m_imageHeight);
     // Convert world origin to camera's world space
     ngl::Vec3 rayOrigin = (ngl::Vec4() * _context->m_renderCamera->getWorldSpaceMatrix()).toVec3();
     // Much improved performance (even without using threads)
     // http://www.iquilezles.org/www/articles/cputiles/cputiles.htm
     const int tilesize = 8;
     const int numxtiles = _context->m_imageWidth / tilesize;
     const int numytiles = _context->m_imageHeight / tilesize;
     const int numtiles = numxtiles * numytiles;
     // Render tiles
     for(int tile=0; tile < numtiles; tile++)
     {
       const int ia = tilesize * (tile % numxtiles);
       const int ja = tilesize * (tile / numxtiles);
       // Compute colour for each pixel in this tile
       for(unsigned int j = 0; j < tilesize; ++j)
       {
         for(unsigned int i = 0; i < tilesize; ++i)
         {
             Image::Pixel result;
             const int samples = _context->m_samples;
             for(int s = 0; s < samples; s++)
             {
                 float jitterX = drand48();
                 float jitterY = drand48();
                 // Canonical Coordinates (camera space)
                 // The jitter is necessary for path tracing to get a variety of samples, but also provides free anti-aliasing
                 float x = (2 * ((ia + i + jitterX) / _context->m_imageWidth) - 1) * _context->m_aspectRatio * _context->m_renderCamera->getAngle();
                 float y = (1 - 2 *((ja + j + jitterY) / _context->m_imageHeight)) * _context->m_renderCamera->getAngle();
                 ngl::Vec3 cameraPosition = (ngl::Vec4(x, y, -1, 1) * _context->m_renderCamera->getWorldSpaceMatrix()).toVec3();
                 ngl::Vec3 rayDirection = cameraPosition - rayOrigin;
                 rayDirection.normalize();
                 // Construct a ray from camera into the world (World Space)
                 Ray ray(rayOrigin,
                         rayDirection,
                         Ray::CAMERA,
                         _context->m_renderCamera->getNearClipPlane(),
                         _context->m_renderCamera->getfarClipPlane()
                         );
                 _context->m_depth = 0;
                 result += trace(ray, _context);
             }
           result /= samples;
           image.setPixel(result, ia + i, ja + j);
         }
       }
       const float percentile = (float)(tile * 1.0 / numtiles) * 100;
       qDebug("Render progress : %.2f%%", percentile);
     }
     qDebug("Render complete.");
     if(_context->m_outputPath.length() > 0)
     {
       image.save(_context->m_outputPath);
     }
     else
     {
       qWarning("Empty output path");
     }
   }
Image::Pixel Renderer::shade (RenderContext * _context)
shade checks if the last ray intersection is shaded by another object or has a clear path to a light source
Parameters
_context stores scene information that needs to be passed between all parts of the pipeline
Returns
the sum of all the light flux affecting this pixel
Todo:
Refraction, snell's law?
Definition at line 9 of file renderer.cpp.
References Material::EMISSIVE, Renderer::Primitive::getNormal(), inverseSquare(), Renderer::RenderContext::m_depth, Renderer::RenderContext::m_hit, Renderer::HitData::m_object, Renderer::HitData::m_ray, Renderer::RenderContext::m_scene, Renderer::HitData::m_surfaceImpact, Renderer::HitData::m_surfaceNormal, Renderer::Scene::objectBegin(), Renderer::Scene::objectEnd(), Renderer::Ray::REFLECT, Renderer::Ray::SHADOW, trace(), transformNormal(), transformPosition(), and Renderer::Primitive::worldTransform().
   {
     Image::Pixel emitted(0, 0, 0);
     Image::Pixel reflected(0, 0, 0);
     // Start the shadow ray from the intersection point
     // The impact point was in object space, we must convert it to world space for it to be useful
     ngl::Vec3 shadowOrigin = transformPosition(_context->m_hit.m_surfaceImpact, _context->m_hit.m_object->worldTransform());;
     // Correct possibility of intersecting with the surface itself,
     // by offsetting it very slightly along the normal (also in world space)
     ngl::Vec3 worldSpaceNormal = transformNormal(_context->m_hit.m_surfaceNormal, _context->m_hit.m_object->worldTransform());
     shadowOrigin += worldSpaceNormal * 0.005f;
     // Gather light from all emissive surfaces in the scene
     for(Scene::objectListIterator light = _context->m_scene->objectBegin();
         light != _context->m_scene->objectEnd();
         light++)
     {
       if( (*light)->getSurfaceMaterial().m_type == Material::EMISSIVE)
       {
           ngl::Vec3 sample = (*light)->sample();
           // Sample a random point on the emissive surface, then convert to world space
           ngl::Vec3 shadowEnd = transformPosition( sample, (*light)->worldTransform() );
           // Calculate the world space direction vector
           ngl::Vec3 direction = shadowOrigin - shadowEnd;
           direction.normalize();
           // Don't bother with checking objects in the scene if the surface normal & light direction are in opposing directions
           // http://www.ics.uci.edu/~gopi/CS211B/RayTracing%20tutorial.pdf pg 8
           if(_context->m_hit.m_object->getNormal(shadowOrigin).dot(direction) <= 0.f)
           {
               continue;
           }
           HitData hitResult;
           bool isShaded = false;
           // Check for an intersection against any object in the scene
           for(Scene::objectListIterator object = _context->m_scene->objectBegin();
               object != _context->m_scene->objectEnd();
               object++)
           {
               Material::SurfaceProperty type = (*object)->getSurfaceMaterial().m_type;
               if( type != Material::EMISSIVE)
               {
                   Ray newRay(shadowOrigin, direction, Ray::SHADOW);
                   // Convert to object space for intersection
                   newRay = (*object)->Primitive::rayToObjectSpace(newRay);
                   if((*object)->intersect(newRay, hitResult))
                   {
                      isShaded = true;
                      break; // If we collide with one object we know this pixel is shaded, no need to check the rest of the scene
                   }
               }
           }
           if(!isShaded)
           {
               Ray tmp(hitResult.m_ray);
               ngl::Colour tint = (*light)->getSurfaceMaterial().m_diffuse;
               ngl::Vec3 camera = shadowOrigin;
               ngl::Vec3 shadow = shadowEnd;
               // Convert sample point to world space
               //shadow = transformPosition(shadow, (*light)->worldTransform());
               float distance = (camera - shadow).length(); // This should be squared, for some reason the actual length computes a nicer falloff
               emitted += Image::Pixel(tint.m_r, tint.m_g, tint.m_b) * inverseSquare(distance);
           }
       }
     }
     // Reflections look terrible right now, let's turn them off
     bool enableReflectionTest = false;
     _context->m_depth++;
     // Hard limit to the depth (4 is a magic number for now, we should move it into render settings)
     if(enableReflectionTest && _context->m_depth < 4)
     {
         // Assume equal chance of reflection or refraction
         if(drand48() > 0.5)
         {
             ngl::Vec3 reflectedDir(shadowOrigin.reflect(worldSpaceNormal));
             reflectedDir += ngl::Vec3(drand48(), drand48(),drand48() );
             Ray reflectedRay(shadowOrigin, reflectedDir, Ray::REFLECT);
             reflected = trace(reflectedRay, _context) * pow(0.25, _context->m_depth);
         }
         else
         {
 //          float theta =
 //          // http://graphics.stanford.edu/courses/cs148-10-summer/docs/2006--degreve--reflection_refraction.pdf
 //          Ray refracted(shadowOrigin, shadowOrigin.reflect(worldSpaceNormal), Ray::REFRACT);
 //          colour += trace(refracted, _context) * pow(0.5, _context->m_depth) ;
         }
     }
     return emitted + reflected;
   }
Image::Pixel Renderer::trace (const Ray & _ray, RenderContext * _context)
trace checks if _ray intersects with anything in the scene
Parameters
_ray Is expected to be a camera ray in world space
_context stores scene information that needs to be passed between all parts of the pipeline
Returns
the background colour if there was no hit, or the result of the shade function otherwise
Bug:
Depth fails completely right now, checking for t value failed too Objects are drawn in order they were read from the file, this could be related to the sphere rendering errors
Definition at line 119 of file renderer.cpp.
References Renderer::Scene::getBackgroundColour(), Renderer::Primitive::getSurfaceMaterial(), Material::m_diffuse, Renderer::RenderContext::m_hit, Renderer::HitData::m_object, Renderer::Ray::m_origin, Renderer::RenderContext::m_scene, Renderer::HitData::m_surfaceImpact, Renderer::Ray::m_tmax, Renderer::Scene::objectBegin(), Renderer::Scene::objectEnd(), shade(), transformPosition(), and Renderer::Primitive::worldTransform().
   {
     HitData hitResult;
     const Primitive* collidingObject = NULL;
     float nearestHit = _ray(_ray.m_tmax).length(); // Get maximum length ray
     float distance = _ray(_ray.m_tmax).length();
     for(Scene::objectListIterator object = _context->m_scene->objectBegin();
         object != _context->m_scene->objectEnd();
         object++)
     {
       // Construct a ray in the primitive's object space and check for collision
       Ray newRay = (*object)->rayToObjectSpace(_ray);
       if( (*object)->intersect(newRay, hitResult) )
       {
         ngl::Vec3 camera = _ray.m_origin;
         ngl::Vec3 shadow = hitResult.m_surfaceImpact;
         // Convert to world space
         shadow = transformPosition(shadow, hitResult.m_object->worldTransform());
         distance = (camera - shadow).length();
         if(distance < nearestHit)
         {
           nearestHit = -distance;
           collidingObject = hitResult.m_object;
         }
       }
     }
     Image::Pixel finalColour;
     if(collidingObject != NULL)
     {
         _context->m_hit = hitResult;
         finalColour = Image::Pixel(_context->m_hit.m_object->getSurfaceMaterial().m_diffuse) * shade(_context);
     }
     else
     {
         finalColour = _context->m_scene->getBackgroundColour();
     }
     return finalColour;
   }
Variable Documentation
const double Renderer::EPSILON = 1.0e-6
Definition at line 33 of file primitive.h.