AffineTransform: Image::Pixel Struct Reference
Image::Pixel Struct Reference
The Pixel struct simply represents an RGB colour, overloads the +,-,/ and * operators.
#include <image.h>
Public Member Functions
Pixel (float _r=0.0f, float _g=0.0f, float _b=0.0f)
Pixel (const ngl::Colour &_colour)
Pixel operator+ (const Pixel &_t)
Pixel operator- (const Pixel &_t)
Pixel operator/ (const Pixel &_t)
Pixel operator* (const Pixel &_t)
Pixel operator/ (float _t)
Pixel operator* (float _t)
void operator+= (const Pixel &_t)
void operator-= (const Pixel &_t)
void operator*= (const Pixel &_t)
void operator/= (const Pixel &_t)
void operator*= (float _t)
void operator/= (float _t)
Public Attributes
float m_r
float m_g
float m_b
Detailed Description
The Pixel struct simply represents an RGB colour, overloads the +,-,/ and * operators.
Definition at line 18 of file image.h.
Constructor & Destructor Documentation
Image::Pixel::Pixel (float _r = 0.0f, float _g = 0.0f, float _b = 0.0f) inline
Definition at line 24 of file image.h.
         : m_r(_r), m_g(_g), m_b(_b) {;}
Image::Pixel::Pixel (const ngl::Colour & _colour) inline
Definition at line 27 of file image.h.
       : m_r(_colour.m_r), m_g(_colour.m_g), m_b(_colour.m_b) {;}
Member Function Documentation
Pixel Image::Pixel::operator* (const Pixel & _t) inline
Definition at line 33 of file image.h.
References m_b, m_g, m_r, and Pixel().
 {   return Pixel( m_r * _t.m_r, m_g * _t.m_g, m_b * _t.m_b );   }
Pixel Image::Pixel::operator* (float _t) inline
Definition at line 35 of file image.h.
References Pixel().
 {   return Pixel( m_r * _t, m_g * _t, m_b * _t );   }
void Image::Pixel::operator*= (const Pixel & _t) inline
Definition at line 39 of file image.h.
 {   *this = *this * _t;  }
void Image::Pixel::operator*= (float _t) inline
Definition at line 41 of file image.h.
 {   *this = *this * _t;  }
Pixel Image::Pixel::operator+ (const Pixel & _t) inline
Definition at line 30 of file image.h.
References m_b, m_g, m_r, and Pixel().
 {   return Pixel( m_r + _t.m_r, m_g + _t.m_g, m_b + _t.m_b );   }
void Image::Pixel::operator+= (const Pixel & _t) inline
Definition at line 37 of file image.h.
 {   *this = *this + _t;  }
Pixel Image::Pixel::operator- (const Pixel & _t) inline
Definition at line 31 of file image.h.
References m_b, m_g, m_r, and Pixel().
 {   return Pixel( m_r - _t.m_r, m_g - _t.m_g, m_b - _t.m_b );   }
void Image::Pixel::operator-= (const Pixel & _t) inline
Definition at line 38 of file image.h.
 {   *this = *this - _t;  }
Pixel Image::Pixel::operator/ (const Pixel & _t) inline
Definition at line 32 of file image.h.
References m_b, m_g, m_r, and Pixel().
 {   return Pixel( m_r / _t.m_r, m_g / _t.m_g, m_b / _t.m_b );   }
Pixel Image::Pixel::operator/ (float _t) inline
Definition at line 34 of file image.h.
References Pixel().
 {   return Pixel( m_r / _t, m_g / _t, m_b / _t );   }
void Image::Pixel::operator/= (const Pixel & _t) inline
Definition at line 40 of file image.h.
 {   *this = *this / _t;  }
void Image::Pixel::operator/= (float _t) inline
Definition at line 42 of file image.h.
 {   *this = *this / _t;  }
Member Data Documentation
float Image::Pixel::m_b
Definition at line 22 of file image.h.
float Image::Pixel::m_g
Definition at line 21 of file image.h.
float Image::Pixel::m_r
Definition at line 20 of file image.h.
The documentation for this struct was generated from the following file:
image.h