AffineTransform: Renderer::SceneFile Class Reference
Renderer::SceneFile Class Reference
The SceneFile class parses a text file for scene information and constructs a new scene from it.
#include <scenefile.h>
Public Member Functions
SceneFile (const std::string &_path)
SceneFile opens the file in _path, ready for reading.
~SceneFile ()
Scene * read ()
reads the system path stored in m_sceneFile
Private Member Functions
ngl::Mat4 parseTransform (std::deque< std::string > &_tokens)
parseTransform Parses a stream of tokens containing position, scale & rotation and constructing a transform matrix from it.
ngl::Colour parseColour (std::deque< std::string > &_tokens)
parseColour Parses a stream of tokens and extracts the r,g,b colour values
ngl::Vec3 parseVertex (std::deque< std::string > &_tokens)
parseVertex Parses a stream of tokens and extracts the x,y,z values
float parseFloat (const std::string &_token)
parseFloat Parses a token and extracts the float value
Material::SurfaceProperty parseMaterialType (const std::string &_token)
parseMaterialType Reads a token to find out the material type
Sphere * parseSphere (std::deque< std::string > &_tokens)
parseSphere Reads a series of tokens to find out spherical data
Triangle * parseTriangle (std::deque< std::string > &_tokens)
parseTriangle Reads a series of tokens to find out triangle data
Camera * parseCamera (std::deque< std::string > &_tokens)
parseCamera Reads a series of tokens to find out camera data
Private Attributes
std::ifstream * m_sceneFile
unsigned int m_counter
m_counter stores the current line number
Detailed Description
The SceneFile class parses a text file for scene information and constructs a new scene from it.
Definition at line 22 of file scenefile.h.
Constructor & Destructor Documentation
Renderer::SceneFile::SceneFile (const std::string & _path)
SceneFile opens the file in _path, ready for reading.
Parameters
_path system path
Exceptions
std::invalid_argument is _path is invalid
Definition at line 23 of file scenefile.cpp.
References m_sceneFile.
   : m_sceneFile(NULL), m_counter(1)
 {
   m_sceneFile = new std::ifstream(_path.c_str(), std::ifstream::in | std::ifstream::out);
   if(!m_sceneFile->is_open())
   {
     throw std::invalid_argument("Scenefile does not exist : " + _path);
   }
 }
Renderer::SceneFile::~SceneFile ()
Definition at line 34 of file scenefile.cpp.
References m_sceneFile.
 {
   m_sceneFile->close();
   delete m_sceneFile;
 }
Member Function Documentation
Camera * Renderer::SceneFile::parseCamera (std::deque< std::string > & _tokens) private
parseCamera Reads a series of tokens to find out camera data
Parameters
_tokens Expects 11 tokens
Returns
Constructs a new camera and returns it
Definition at line 331 of file scenefile.cpp.
References m_counter, parseFloat(), and parseTransform().
 {
   ngl::Mat4 transform;
   float FOV;
   float nearZ = 0.0f, farZ = 1e9;
   try
   {
     transform = parseTransform(_tokens);
     FOV = parseFloat( popFirstItem<std::string>(_tokens) );
     nearZ = parseFloat( popFirstItem<std::string>(_tokens) );
     farZ = parseFloat( popFirstItem<std::string>(_tokens) );
   }
   catch(std::runtime_error& e)
   {
     std::cerr  << "Line " << m_counter << " : Error parsing camera data : " << e.what() << std::endl;
     return NULL;
   }
   return new Camera(transform, FOV, nearZ, farZ);
 }
ngl::Colour Renderer::SceneFile::parseColour (std::deque< std::string > & _tokens) private
parseColour Parses a stream of tokens and extracts the r,g,b colour values
Parameters
_tokens Expects 3 strings from start index of token stream, of the form r,g,b
_tokenOffset is the start index of the token stream
Returns
an rgb colour std::runtime_error is returned if the token stream is too short
Definition at line 169 of file scenefile.cpp.
References tokenToFloat().
 {
   ngl::Colour colour;
   if(_tokens.size() < 3)
   {
       throw std::runtime_error("Could not read colour");
   }
   colour = ngl::Colour( tokenToFloat(popFirstItem<std::string>(_tokens)),
                         tokenToFloat(popFirstItem<std::string>(_tokens)),
                         tokenToFloat(popFirstItem<std::string>(_tokens)) );
   return colour;
 }
float Renderer::SceneFile::parseFloat (const std::string & _token) private
parseFloat Parses a token and extracts the float value
Parameters
_tokens Expects 1 string token
Returns
a float value std::runtime_error is returned if the token could not be read
Definition at line 201 of file scenefile.cpp.
References tokenToFloat().
 {
   float val;
   try
   {
     val = tokenToFloat(_token);
   }
   catch(std::runtime_error)
   {
     throw std::runtime_error("Could not read float value");
   }
   return val;
 }
Material::SurfaceProperty Renderer::SceneFile::parseMaterialType (const std::string & _token) private
parseMaterialType Reads a token to find out the material type
Parameters
_token A string value
Returns
The parsed material type
Definition at line 217 of file scenefile.cpp.
References Material::DIFFUSE, Material::EMISSIVE, and Material::SPECULAR.
 {
     if(_token == "DIFFUSE")         return Material::DIFFUSE;
     else if (_token == "SPECULAR")  return Material::SPECULAR;
     else if (_token == "EMISSIVE")  return Material::EMISSIVE;
     else
         throw std::runtime_error("Unknown material ");
     return Material::DIFFUSE;
 }
Sphere * Renderer::SceneFile::parseSphere (std::deque< std::string > & _tokens) private
parseSphere Reads a series of tokens to find out spherical data
Parameters
_tokens Expects 13 tokens
Returns
Constructs a new sphere and returns it
Definition at line 229 of file scenefile.cpp.
References parseColour(), parseMaterialType(), and parseTransform().
 {
   /*
    * $sphere tx ty tz sx sy sz rx ry rz cr cg cb
    */
   ngl::Mat4 transform;
   ngl::Colour colour;
   Material::SurfaceProperty type;
   try
   {
     transform = parseTransform(_tokens);
     colour = parseColour(_tokens);
     type = parseMaterialType( _tokens[0] );
   }
   catch(std::runtime_error& e)
   {
     std::cerr << " : Error parsing sphere data : " << e.what() << std::endl;
     return NULL;
   }
   Material mat(type, colour);
   return new Sphere(transform, mat, 1.0f);
 }
ngl::Mat4 Renderer::SceneFile::parseTransform (std::deque< std::string > & _tokens) private
parseTransform Parses a stream of tokens containing position, scale & rotation and constructing a transform matrix from it.
Parameters
_tokens Expects 9 strings from start index of token stream, of the form px, py, pz, sx, sy, sz, rx, ry, rz
_tokenOffset is the start index of the token stream
Returns
a transform matrix, M = Translation * Rotation * Scale std::runtime_error is returned if the token stream is too short
Definition at line 134 of file scenefile.cpp.
References tokenToFloat().
 {
   ngl::Vec3 position, rotation, scale;
   if(_tokens.size() < 9)        { throw std::runtime_error("Could not read rotation"); }
   else if(_tokens.size() < 6)   { throw std::runtime_error("Could not read scale"); }
   else if(_tokens.size() < 3)   { throw std::runtime_error("Could not read position"); }
     position = ngl::Vec3( tokenToFloat(popFirstItem<std::string>(_tokens)),
                   tokenToFloat(popFirstItem<std::string>(_tokens)),
                   tokenToFloat(popFirstItem<std::string>(_tokens)) );
     scale = ngl::Vec3( tokenToFloat(popFirstItem<std::string>(_tokens)),
                  tokenToFloat(popFirstItem<std::string>(_tokens)),
                  tokenToFloat(popFirstItem<std::string>(_tokens)) );
     rotation = ngl::Vec3( tokenToFloat(popFirstItem<std::string>(_tokens)),
                     tokenToFloat(popFirstItem<std::string>(_tokens)),
                     tokenToFloat(popFirstItem<std::string>(_tokens)) );
   ngl::Mat4 translateXYZ, scaleXYZ, rotX, rotY, rotZ;
   rotX.rotateX(rotation.m_x);
   rotY.rotateY(rotation.m_y);
   rotZ.rotateZ(rotation.m_z);
   translateXYZ.translate(position.m_x, position.m_y, position.m_z);
   scaleXYZ.scale(scale.m_x, scale.m_y, scale.m_z);
   ngl::Mat4 result;
   result = translateXYZ * rotZ * rotY * rotX * scaleXYZ;
   return result;
 }
Triangle * Renderer::SceneFile::parseTriangle (std::deque< std::string > & _tokens) private
parseTriangle Reads a series of tokens to find out triangle data
Parameters
_tokens Expects 21 tokens
Returns
Constructs a new triangle and returns it
Definition at line 256 of file scenefile.cpp.
References m_counter, Material::m_diffuse, parseColour(), parseMaterialType(), parseTransform(), and parseVertex().
 {
     /*
     * $tri v0x v0y v0z v1x v1y v1z v2x v2y v2z tx ty tz sx sy sz rx ry rz cr cg cb
     */
    ngl::Mat4 transform;
    ngl::Colour colour;
    ngl::Vec3 vertex[3];
    Material::SurfaceProperty type;
    try
    {
      vertex[0] = parseVertex(_tokens);
      vertex[1] = parseVertex(_tokens);
      vertex[2] = parseVertex(_tokens);
      transform = parseTransform(_tokens);
      colour = parseColour(_tokens);
      type = parseMaterialType( _tokens[0] );
    }
    catch(std::runtime_error& e)
    {
      std::cerr << "Line " << m_counter << " : Error parsing triangle data : " << e.what() << std::endl;
      return NULL;
    }
    Material mat(type, colour);
    mat.m_diffuse.m_r = colour.m_r;
    mat.m_diffuse.m_g = colour.m_g;
    mat.m_diffuse.m_b = colour.m_b;
 //   mat.m_type = type;
    return new Triangle(vertex[0], vertex[1], vertex[2], transform, mat);
 }
ngl::Vec3 Renderer::SceneFile::parseVertex (std::deque< std::string > & _tokens) private
parseVertex Parses a stream of tokens and extracts the x,y,z values
Parameters
_tokens Expects 3 strings from start index of token stream, of the form x,y,z
_tokenOffset is the start index of the token stream
Returns
a vector std::runtime_error is returned if the token stream is too short
Definition at line 185 of file scenefile.cpp.
References tokenToFloat().
 {
   ngl::Vec3 vtx;
   if(_tokens.size() < 3)
   {
       throw std::runtime_error("Could not read vertex");
   }
   vtx = ngl::Vec3( tokenToFloat(popFirstItem<std::string>(_tokens)),
                    tokenToFloat(popFirstItem<std::string>(_tokens)),
                    tokenToFloat(popFirstItem<std::string>(_tokens)) );
   return vtx;
 }
Renderer::Scene * Renderer::SceneFile::read ()
reads the system path stored in m_sceneFile
Returns
constructs a scene and returns it based on the file data
Definition at line 40 of file scenefile.cpp.
References Renderer::Camera::getWorldSpaceMatrix(), m_counter, m_sceneFile, parseCamera(), parseFloat(), parseSphere(), parseTriangle(), and tokenize().
 {
   Scene::objectList primitives;
   Camera* renderCamera = NULL; // Only allow 1 render camera, maybe extend to support many cameras in scenes
   Image::Pixel background(0.5, 0.5, 0.5); // Background colour
   std::string line;
   while ( std::getline(*m_sceneFile, line) )
   {
     std::vector<std::string> tokenVector;
     tokenize(line, tokenVector, " \t");
     std::deque<std::string> tokens;
     std::copy( tokenVector.begin(), tokenVector.end(), std::inserter( tokens, tokens.end() ) );
     if(tokens.size() > 0)
     {
       std::string lineType = popFirstItem<std::string>(tokens);
       if(lineType[0] != '#' && lineType[0] == '$') // Ignore lines not starting with $ and are not comments #
       {
         lineType.erase(0, 1);
         if(lineType == "camera")
         {
           if(renderCamera)
           {
             std::cerr << "More than one camera found, using first camera\n";
           }
           else
           {
             renderCamera = parseCamera(tokens);
           }
         }
         else if(lineType == "background")
         {
             try
             {
               background = Image::Pixel(parseFloat(popFirstItem<std::string>(tokens)),
                                        parseFloat(popFirstItem<std::string>(tokens)),
                                        parseFloat(popFirstItem<std::string>(tokens)));
             }
             catch(std::runtime_error& e)
             {
               std::cerr << "Error parsing background data : " << e.what() << std::endl;
             }
         }
         else if(lineType == "sphere")
         {
           Sphere* primitive = parseSphere(tokens);
           if(primitive)
             primitives.push_back(primitive);
         }
         else if(lineType == "tri")
         {
           Triangle* primitive = parseTriangle(tokens);
           if(primitive)
             primitives.push_back(primitive);
         }
 //        else if(lineType == "plane")
 //        {
 //          Plane* primitive = parsePlane(tokens);
 //          if(primitive)
 //            primitives.push_back(primitive);
 //        }
         /* Doesn't make much sense to store render data like resolution in the scene file */
 //        else if(lineType == "res")
 //        {
 //          try
 //          {
 //            xres = parseFloat(popFirstItem<std::string>(tokens));
 //            yres = parseFloat(popFirstItem<std::string>(tokens));
 //          }
 //          catch(std::runtime_error& e)
 //          {
 //            std::cerr << "Error parsing resolution data : " << e.what() << std::endl;
 //          }
 //        }
         else
         {
             //std::cerr << "Unknown data type : " << lineType << std::endl;
         }
       } // End $ check
     } // End token size check
     m_counter++;
   } // End line loop
   if(!renderCamera)
       renderCamera = new Camera;
   return new Scene(primitives, renderCamera->getWorldSpaceMatrix(), background);
 }
Member Data Documentation
unsigned int Renderer::SceneFile::m_counter private
m_counter stores the current line number
Definition at line 116 of file scenefile.h.
std::ifstream* Renderer::SceneFile::m_sceneFile private
Definition at line 42 of file scenefile.h.
The documentation for this class was generated from the following files:
scenefile.h
scenefile.cpp